[tools]
tailwindcss = "4.1.13"

[watch]
watch = ["src", "../bots/src"]


[serve]
headers = {"Cross-Origin-Opener-Policy" = "same-origin","Cross-Origin-Embedder-Policy" = "require-corp"}
port = 8090                #